version: '3.1'
services:
  test-back:
    container_name: restaurant-db
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: restaurant