-- CREATE TABLE "product" (
--                            "uuid" smallserial PRIMARY KEY NOT NULL,
--                            "name" varchar(255),
--                            "description" varchar,
--                            "type_id" smallint,
--                            "weight" smallint,
--                            "price" double precision(2),
--                            "created_at" timestamp
-- );
--
-- CREATE TABLE "type" (
--                         "id" smallint PRIMARY KEY,
--                         "type" varchar
-- );
--
-- CREATE TABLE "menu" (
--                         "uuid" smallserial PRIMARY KEY NOT NULL,
--                         "on_date" timestamp,
--                         "opening_record_at" timestamp,
--                         "closing_record_at" timestamp,
--                         "salad" smallint,
--                         "garnish" smallint,
--                         "meat" smallint,
--                         "soup" smallint,
--                         "drink" smallint,
--                         "dessert" smallint
-- );
--
-- CREATE TABLE "order_by_office" (
--                                    "id" smallserial PRIMARY KEY NOT NULL,
--                                    "office_uuid" smallint,
--                                    "office_name" varchar(255),
--                                    "office_adress" varchar,
--                                    "order_id" smallint
-- );
--
-- CREATE TABLE "order" (
--                          "id" smallserial PRIMARY KEY NOT NULL,
--                          "product_id" smallint,
--                          "product_name" varchar(255),
--                          "count" smallint
-- );
--
-- CREATE TABLE "orders_on_date" (
--                                   "id" timestamp PRIMARY KEY DEFAULT (now()),
--                                   "total_orders" smallint,
--                                   "total_by_company" smallint
-- );
--
-- ALTER TABLE "product" ADD FOREIGN KEY ("type_id") REFERENCES "type" ("id");
--
-- ALTER TABLE "menu" ADD FOREIGN KEY ("salad") REFERENCES "product" ("uuid");
--
-- ALTER TABLE "menu" ADD FOREIGN KEY ("garnish") REFERENCES "product" ("uuid");
--
-- ALTER TABLE "menu" ADD FOREIGN KEY ("meat") REFERENCES "product" ("uuid");
--
-- ALTER TABLE "menu" ADD FOREIGN KEY ("soup") REFERENCES "product" ("uuid");
--
-- ALTER TABLE "menu" ADD FOREIGN KEY ("drink") REFERENCES "product" ("uuid");
--
-- ALTER TABLE "menu" ADD FOREIGN KEY ("dessert") REFERENCES "product" ("uuid");
--
-- ALTER TABLE "order_by_office" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");
--
-- ALTER TABLE "order" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("uuid");
--
-- ALTER TABLE "order" ADD FOREIGN KEY ("product_name") REFERENCES "product" ("name");
--
-- ALTER TABLE "orders_on_date" ADD FOREIGN KEY ("total_orders") REFERENCES "order" ("id");
--
-- ALTER TABLE "orders_on_date" ADD FOREIGN KEY ("total_by_company") REFERENCES "order_by_office" ("id");
