package handlers

import (
	"context"
	"fmt"
	"log"

	pb "github.com/MikhailMishutkin/FoodOrdering/pkg/contracts-v0.3.0/pkg/contracts/restaurant"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

//generated by package gen
func (s *RestaurantService) CreateProduct(ctx context.Context, in *pb.CreateProductRequest) (*pb.CreateProductResponse, error) {
	log.Print("CreateProduct was invoked")

	p := new(pb.Product)
	err := s.repoR.CreateProduct(p)

	if err != nil {
		code := codes.Internal
		return nil, status.Errorf(code, "repo.CreateProduct went down witn error, cannot save product in db: %v\n", err)
	}

	resp := &pb.CreateProductResponse{}

	return resp, nil
}

func (s *RestaurantService) GetProductList(ctx context.Context, in *pb.GetProductListRequest) (*pb.GetProductListResponse, error) {
	log.Print("GetProductList was invoked")
	res, err := s.repoR.GetProductList()
	if err != nil {
		code := codes.Internal
		return nil, status.Errorf(code, "repo.GetProductList went down witn error, cannot get products from db: %v\n", err)
	}
	//TODO: delete
	fmt.Println(res.Result)
	return res, nil
}
